### ISSUE TITLE
BulletSharp 2.83 Binaries

### ISSUE THREAD

**Issue by dazerdude** [AndresTraks/BulletSharp#17]
I've been trying to build the 2.83 binaries using the Build Instructions on the old google code page, but it isn't very straightforward, especially when I spend most of my time in c# land. Before I simply used the prebuilt x64 binaries available on the google code download page and everything worked swimmingly.

Is there a place where the 2.83 Binaries are hosted, or do I need to go through the full build process to get them?

**Comment by AndresTraks** [comment]
The binary downloads are at the bottom left of the page:
https://code.google.com/p/bulletsharp/

**Comment by dazerdude** [comment]
Sweet. That was not at all obvious to me. Thanks!
