### ISSUE TITLE
TriangleMeshShape has no constructors defined?

### ISSUE THREAD

**Issue by mcmonkey4eva** [AndresTraks/BulletSharp#18]
I tried a few different versions of BulletSharp, including 2.83, and they all say 'TriangleMeshShape has no constructors defined', making me think it's not implemented. Is there an alternate version with it defined / an alternate way to make a non-convex dynamically shaped mesh?
I notice TriangleMesh exists and works, but I can't seem to find a way to use that as a RigidBody's shape.
EDIT: Aha. `BvhTriangleMeshShape` exists - why the Bvh prefix?
EDIT2: ... is it because it tends to throw SystemAccessViolationException's? Cause that happens...

```
nhandled Exception: System.AccessViolationException: Attempted to read or write
protected memory. This is often an indication that other memory is corrupt.
  at btBvhTriangleMeshShape.{ctor}(btBvhTriangleMeshShape* , btStridingMeshInte
face* , Boolean , Boolean )
  at BulletSharp.BvhTriangleMeshShape..ctor(StridingMeshInterface meshInterface
 Boolean useQuantizedAabbCompression)
  at Voxalia.ClientGame.WorldSystem.Chunk.UpdateVBO() in C:\Github\Voxalia\Voxa
ia\ClientGame\WorldSystem\Chunk.cs:line 234
```
Line 234:
`            BvhTriangleMeshShape trianglemesh = new BvhTriangleMeshShape(mesh, true);`
EDIT: Oh, that's because I had 0 triangles for that particular call. Heh.

Okay, this entire issue is now just to ask why it's "Bvh" prefixed and how that affects using it.

**Comment by AndresTraks** [comment]
I'll add checks to the BvhTriangleMeshShape constructor. TriangleMeshShape is just an interface that describes the behaviour of triangle mesh shapes. BvhTriangleMeshShape is a concrete implementation of a triangle mesh shape that uses a Bounding Volume Hierarchy as an optimization.

Some documentation for it is here:
http://bulletphysics.org/Bullet/BulletFull/classbtBvhTriangleMeshShape.html

For dynamic (moving) shapes, it's better to use ConvexHullShape or GimpactMeshShape. You can find documentation on Google if you add the bt prefix ("btGimpactMeshShape") and there are demos in this repository for both.
