### ISSUE TITLE
Download dll for BulletSharp 2.83 differs from the one in Demos projects

### ISSUE THREAD

**Issue by ChrisSchneebauer** [AndresTraks/BulletSharp#19]
I did an upgrade to your latest BulletSharp version 2.83, but could not compile because Matrix and Vector3 weren't available in the dll. Using those from SharpDX didn't work either. Then I checked your Demo projects and saw that the dll used there differs a few bytes, although having the same version number. Taking the dll from Demos I was able to compile.

**Comment by ChristinaSchneebauer** [comment]
Forgot to mention, it's about the SharpDX BulletSharp dll.

**Comment by AndresTraks** [comment]
Only the dll in the "Release Generic" folder will have the Matrix and Vector3 classes. Others such as the SharpDX version will use Matrix/Vector3 classes from SharpDX.

The demos also use the Generic version, because it's not dependant on any external library and so you can switch between graphics frameworks (by pressing F8).

**Comment by ChristinaSchneebauer** [comment]
Thank you for the quick answer! Totally makes sense. But then I think my problem is that the BulletSharp dll is built with the unsigned SharpDX dll. Is this possible? As we're using the signed one, it won't compile.

**Comment by AndresTraks** [comment]
Yes, it's linked to the unsigned version. I'll provide a version linked to signed SharpDX in the future. This must be related to https://code.google.com/p/bulletsharp/issues/detail?id=73
For now, you could compile BulletSharp manually if you need this.

**Comment by AndresTraks** [comment]
2.83.5 includes a version for signed SharpDX:
https://drive.google.com/folderview?id=0B2TPMwtggT0jfmRzRm1RQkJOYjZXVWV6Y2FwZGxKV1cxWE1ZTVlWd2paZ2RWLTE5MTEtMEk#list
