### ISSUE TITLE
Access violation in BulletSharp when freeing CollisionWorld

### ISSUE THREAD

**Issue by JoeMug** [AndresTraks/BulletSharp#20]
Hi,
with version 2.82 we had sporadic access violations during shutdown of our application.
The update to verision 2.83 did not change this behaviour. 
We downloaded and compiled the BulletSharp/Bullet debug versions. Now the access violation occurs on every shutdown.
In the debugger we can see the crash occur in  !CollisionWorld()-> free _native
We could not debug into the bullet library so we added code from Bullet libraries desctructor to the !CollisionWorld() to track down the error and
found out that bp of : btBroadphaseProxy* bp = collisionObject->getBroadphaseHandle(); 
is not valid and crashes.
Any ideas?

**Comment by AndresTraks** [comment]
Make sure you remove collision objects from the world before you dispose them.

**Comment by mifwarior** [comment]
same exception 
BvhTriangleMeshShape s;
...
s.MeshInterface.Dispose();

**Comment by AndresTraks** [comment]
Well, yes, if you dispose the mesh data that the mesh shape uses, it will crash. That is expected, isn't it?

**Comment by mifwarior** [comment]
Ок, thanks. How to unload TriangleIndexVertexArray, i take a simple test, create TriangleIndexVertexArray, and then dispose in a cycle, I see an increase in memory. But if  is try test with BTbvhTriangleMeshShape, it's ok, memory not growing.

       public static void TriangleTest(int [] triangles, float [] verticles)
        {
            List<TriangleIndexVertexArray> arrays = new List<TriangleIndexVertexArray>();
            for (int n = 0; n < 1000; n++)
            {
                arrays.Add(new TriangleIndexVertexArray(triangles, verticles));
                for (int i = 0; i < arrays.Count; i++)
                {
                    arrays[i].Dispose();
                }
                if (n % 100 == 0) Console.WriteLine(n);
                arrays.Clear();
            }
            GC.Collect();
        }

**Comment by AndresTraks** [comment]
There is indeed a memory leak in TriangleIndexVertexArray, the memory for vertex and triangle data isn't freed. I will fix it within the next week. Thanks for reporting!

**Comment by AndresTraks** [comment]
I've commited a fix for the TriangleIndexVertexArray memory leak.

**Comment by drcrack** [comment]
it still happens with 2.87 x64 when calling Dispose of DiscreteDynamicsWorld

**Comment by drcrack** [comment]
also happens in StepSimulation
