### ISSUE TITLE
LocalShapeInfo always null

### ISSUE THREAD

**Issue by Dreamnoid** [AndresTraks/BulletSharp#21]
Hi,
I'm writing a raytracing renderer, using RayTest() to query my geometry. The raycast works, I get correct values for HitPointWorld and HitNormalWorld, so far so good.

Now, I need the TriangleIndex property to identify the intersection triangle and get its material or UV coordinates. To achieve this, I created a custom callback inheriting ClosestRayResultCallback, hoping to use the LocalShapeInfo property of the LocalRayResult object that is passed to AddSingleResult().

However, the LocalShapeInfo reference is always null :

        public class RaytracerCallback : BT.ClosestRayResultCallback
        {
            public int TriangleIndex { get; private set; }

            public RaytracerCallback ( ref BT.Vector3 from , ref BT.Vector3 to )
                : base ( ref from , ref to )
            {
            }

            public override float AddSingleResult ( BT.LocalRayResult rayResult , bool normalInWorldSpace )
            {
                if ( rayResult.LocalShapeInfo != null )
                {
                    // Never called
                    System.Diagnostics.Debugger.Break ();
                    TriangleIndex = rayResult.LocalShapeInfo.TriangleIndex;
                }
                float result = base.AddSingleResult ( rayResult , normalInWorldSpace );
                return result;
            }
        }

The little documentation I've found on this topic (all for the C++ version) seems to point my code is correct, so I'm left wondering if it is a bug in BulletSharp 2.83 itself?

For what it's worth, it seems to me the "_localShapeInfo" attribute of LocalRayResult, returned by the getter method, is only assigned with the second constructor... when only the first one is used. (But I may be wrong, it's late here!)

Any ideas?

(Oh, and while I'm here, I want to thank you for such a handy wrapper! ;))

**Comment by AndresTraks** [comment]
Yeah, I think it's one of those not so often used pieces of code that was forgotten at some point. I added a quick fix which I'll review it later (it's late here too), but you can try it out.

**Comment by Dreamnoid** [comment]
After some struggle with CMake, I compiled the whole thing, and baring some mistake of my part in the process, it doesn't work: now the LocalShapeInfo getter throws a NullReferenceException instead of merely returning null: 
![bulletsharp_localshapeinfo](https://cloud.githubusercontent.com/assets/11877905/7093740/1e003a20-dfbc-11e4-90c3-35e3cb27b012.jpg)

**Comment by AndresTraks** [comment]
Ah, it was a rushed fix, try the next commit, please. I will add a proper test soon.

**Comment by Dreamnoid** [comment]
It works! Awesome!
Thanks for your outstanding reactivity :+1:
