### ISSUE TITLE
It is not possible to use the GetAabb

### ISSUE THREAD

**Issue by tam7832** [AndresTraks/BulletSharp#23]
Hi
I tried version2.82. The CollisionShape.GetAabb and GImpactMeshShape.GImpactMeshShapePart.GetVertex
from the object that was created in GImpactMeshShape It was called. process exits.

Is there any idea?

**Comment by AndresTraks** [comment]
The C++/CLI compiler is trying to inline this piece of code:
http://bulletphysics.org/Bullet/BulletFull/btGImpactShape_8h_source.html#l00134

But C++/CLI can't allocate the btAABB object with proper memory alignment for SSE like C++ can. I'll try to find a workaround.

**Comment by tam7832** [comment]
Thank you for doing research

**Comment by AndresTraks** [comment]
GetAabb should work now. Is it possible for you to try it? Are you using the old 2.82 version because you need .NET 2.0?

To use GetVertex, you need to do more work. GetVertex requires locking the TrimeshPrimitiveManager, which is only available if you compile without the DISABLE_BVH definition in Stdafx.h. If you only need to get the vertices and not do anything fancy, then you can just use the vertices that you originally passed to the GImpactMeshShape.

This is a largely untested part of BulletSharp since it's not a typical use case. That's why there are these problems.

**Comment by tam7832** [comment]
I'm using the Net 4.5.
Switch to the new version is not a problem, but to a format that can use the earlier version
Problems might occur.

For now, the vertices using the GImpactMeshShape.MeshInterface.GetLockedReadOnlyVertexIndexData
To use so like there is no problem, it is used to determine the AABB.

When the problem is resolved
I want to use it.

**Comment by tam7832** [comment]
Can you use GetAABB In bulletsharp-x64-2.83 / Release SharpDX?

Of after calling GImpactMeshShape () in my environment
The process will be exited somewhere.

Somewhere it seems there is a problem,
It is not been able to find yet.

**Comment by AndresTraks** [comment]
Version 2.83.5 includes the fix for GetAabb.

**Comment by tam7832** [comment]
Hello. I'm sorry, correspondence became slow.
I tried the Version 2.83.5.

I used bulletsharp-x64-2.83.5 / Release SharpDX.

We've created a shape in GImpactMeshShape.
After you create a shape, somewhere in the timing
Process will exit.

Whether the same phenomenon occurs at your place?

**Comment by AndresTraks** [comment]
The GImpact demo works fine:
https://github.com/AndresTraks/BulletSharp/blob/master/demos/Generic/GImpactTestDemo/GImpactTestDemo.cs

Can you share the code where you set up the GImpactMeshShape?

**Comment by tam7832** [comment]
We've checked for proper operation GImpactTestDemo.
There was no problem.

However, when the access to gImpactmesh.LocalBox
The process is terminated.

var minBox = trimesh.LocalBox.Min;

**Comment by tam7832** [comment]
Another problem is there, but GetAABB () There is no problem.
Here will and resolution.
Thank you.
