### ISSUE TITLE
64bit sharpdx demo, access violation

### ISSUE THREAD

**Issue by shinkamui** [AndresTraks/BulletSharp#24]
Hi,
I just download the 2.83 sharpdx demo (BulletSharp/demos/SharpDX/), and found some problems.
I use 64b bulletsharp dll at beginning, and use BasicDemo as inital project. When compile, MeshFatory said it have no definition of  "BroadphaseNativeType.StaticPlaneShape" (DemoFramework/MeshFatory.cs, line 890). Comment, then compile success, but if I change body.Gravity in Physics.cs, it goes access violation. Basiclly I can't modify any value or the violation will appear.
Then I use 32b dll, everything seems good. My system is window 7 64b, please help >_<

**Comment by AndresTraks** [comment]
Yesterday, BroadphaseNativeType.StaticPlane was renamed to StaticPlaneShape for consistency, I think you can just recompile BulletSharp and it will work.
Not sure about the 64-bit problem, will investigate.

**Comment by shinkamui** [comment]
Thanks.
Really anticipate to see 64b dll work >_<

**Comment by shinkamui** [comment]
ps:2.82 x64 version works great ^_^

**Comment by AndresTraks** [comment]
I didn't find any obvious regressions in the 64-bit version. The tests and the demos both seem to work. Can you post your code?

**Comment by shinkamui** [comment]
Sorry I don't know how to compile 2.x bulletsharp, just directly use the compiled dll from "http://andrestraks.github.io/BulletSharp/"

My test code can be down from this url
https://drive.google.com/file/d/0Byc1YaPjaARNb1JxS0tBZzVsaW8/view?usp=sharing

Nearly nothing changed from the original git version

**Comment by AndresTraks** [comment]
Still couldn't reproduce the access violation, but try 2.83.5:
https://drive.google.com/folderview?id=0B2TPMwtggT0jfmRzRm1RQkJOYjZXVWV6Y2FwZGxKV1cxWE1ZTVlWd2paZ2RWLTE5MTEtMEk#list

**Comment by shinkamui** [comment]
Great, 2.83.5 works.
Seems I should learn to compile 2.xx dll by myself.

Thanks
