### ISSUE TITLE
vb.net   .ctor-is-ambiguous-because-multiple-kinds-of-members

### ISSUE THREAD

**Issue by tridexanders** [AndresTraks/BulletSharp#25]
in vb.net these lines are giving erro descibed below, can you help GENERIC bullet sharp dll .. 

       shape.AddChildShape(Matrix.Identity, New BoxShape(5.0!, 1.0!, 6.0!))
        shape.AddChildShape(Matrix.RotationZ(3.141593!), New BoxShape(5.0!, 1.0!, 6.0!))

described here

http://stackoverflow.com/questions/21904767/ctor-is-ambiguous-because-multiple-kinds-of-members-with-this-name-exist-in-cla

**Comment by AndresTraks** [comment]
Yes, the ambiguous methods should be removed. I don't aim for fully CLS-compliant code, but this ambiguity is also a problem in C++/CLI, so I'll fix this soon.

**Comment by tridexanders** [comment]
Thanks for your prompt answer, will keep an eye on project for change, loving the idea of using SIMD as the library has vastly improved , still waiting for full 

release of vs to incorate all that you need to code with SIMD ... 


oh question, how come there are is no more threading with BULLET SHARP 2.8.3 ??  i cannot find it any were .. 

thanks.. Tridex ... 
 


     On Tuesday, June 9, 2015 10:10 PM, Andres Traks <notifications@github.com> wrote:
   

 Yes, the ambiguous methods should be removed. I don't aim for fully CLS-compliant code, but this ambiguity is also a problem in C++/CLI, so I'll fix this soon.—

**Comment by AndresTraks** [comment]
> oh question, how come there are is no more threading with BULLET SHARP 2.8.3 ??  i cannot find it any were ..

They removed the old multithreading code from the 2.xx part of the library in favor of the new bullet3 code, which is built specifically with GPUs in mind. However, now there was a significant improvement of the old code from the community, so it looks like they are going to add the old classes back:
https://github.com/bulletphysics/bullet3/pull/390

**Comment by AndresTraks** [comment]
This issue was actually fixed a couple of weeks ago by renaming the AddChildShape with the ref-parameter to AddChildShapeRef.
https://github.com/AndresTraks/BulletSharp/blob/e4669ddaaf7e31123576e385019d1c0a29684214/src/CompoundShape.cpp#L86

I don't know when bullet 2.84 is coming out, but i could do a 2.83.5 release in the meantime.

**Comment by AndresTraks** [comment]
2.83.5 is released with the fix:
https://drive.google.com/folderview?id=0B2TPMwtggT0jfmRzRm1RQkJOYjZXVWV6Y2FwZGxKV1cxWE1ZTVlWd2paZ2RWLTE5MTEtMEk#list
