### ISSUE TITLE
Unable to compile bulletsharp

### ISSUE THREAD

**Issue by publicENEMY** [AndresTraks/BulletSharp#26]
Followed the instruction here https://github.com/AndresTraks/BulletSharp/wiki/Build-instructions

Using 64 bit. Target Debug Opentk 64bit. 

My error when compiling bulletsharp
Error	17	error LNK1181: cannot open input file 'LinearMath_Debug.lib'	e:\Users\iJam\Source\Repos\BulletSharp\LINK	BulletSharp

**Comment by AndresTraks** [comment]
Make sure that the bullet3 and BulletSharp subfolders are in the same folder (git clone the projects into the same folder).
Make sure that bullet compiled successfully with the Debug configuration and that LinearMath_Debug.lib exists in the folder bullet3\msvc\20xx\lib\Debug. The debug version of BulletSharp uses the debug version of bullet (not MinSizeRel).

**Comment by publicENEMY** [comment]
Heres what i did

1. Cloned bullet3 into e:\Users\iJam\Source\Repos\bullet3
![image](https://cloud.githubusercontent.com/assets/2562219/8143158/22f79a04-11d1-11e5-8a17-8bd5598fc829.png)

2. Cloned bulletsharp into e:\Users\iJam\Source\Repos\bullet3\build3\msvc\2013
![image](https://cloud.githubusercontent.com/assets/2562219/8143159/30db5de0-11d1-11e5-8fca-de698407717b.png)

3. Using cmake-gui create vs2013 solution.
  1. Checked USE_MSVC_RUNTIME_LIBRARY_DLL
  2. Unchecked BUILD_BULLET2_DEMOS, BUILD_CPU_DEMOS, BUILD_OPENGL3_DEMOS
![image](https://cloud.githubusercontent.com/assets/2562219/8143165/429de908-11d1-11e5-9de9-9504d6d1bba3.png)

4. Open bullet3/msvc/20xx/BULLET_PHYSICS.sln and build everything(Debug, Release, MinSizeRel).
![image](https://cloud.githubusercontent.com/assets/2562219/8143168/5b5c7f90-11d1-11e5-98a6-ddcdeed2888c.png)

5. Open bulletsharp solution from e:\Users\iJam\Source\Repos\bullet3\build3\msvc\2013 and e:\Users\iJam\Source\Repos\bullet3\build3\msvc\2013\vs2013. 
![image](https://cloud.githubusercontent.com/assets/2562219/8143172/6f40c796-11d1-11e5-8f6a-84db65437d65.png)

Set target to debug_opentk and release_opentk. 
![image](https://cloud.githubusercontent.com/assets/2562219/8143175/8b8fdb4e-11d1-11e5-8663-b908da1436c8.png)

Add additional using directory to Opentk for debug, release, x86, x64. 
![image](https://cloud.githubusercontent.com/assets/2562219/8143177/b03b3b96-11d1-11e5-824e-d55317e8ccb0.png)

Build any of them(debug, release). Got same error.
Error	1	error C1083: Cannot open include file: 'btBulletCollisionCommon.h': No such file or directory	e:\users\ijam\source\repos\bullet3\build3\msvc\2013\src\stdafx.h	124	1	BulletSharp

**Comment by AndresTraks** [comment]
1. Good.

2. Clone BulletSharp into e:\Users\iJam\Source\Repos\BulletSharp, not e:\Users\iJam\Source\Repos\bullet3\build3\msvc\2013.
 By cloning the projects into the same folder, I mean you should have two folders:
 * e:\Users\iJam\Source\Repos\bullet3 and
 * e:\Users\iJam\Source\Repos\BulletSharp

 The VS 2013 solution of BulletSharp should be in:
 * e:\Users\iJam\Source\Repos\BulletSharp\vs2013\BulletSharp.sln

3. Where to build the binaries: e:/Users/iJam/Source/Repos/bullet3/msvc/2013
(no build3 folder in between).

4. Good (except the build3 part). Build Debug for BulletSharp Debug and MinSizeRel for BulletSharp Release.

5. Should work then.

**Comment by publicENEMY** [comment]
I have successfully compiled bulletsharp thanks to your instruction.
