### ISSUE TITLE
Unable to compile bulletsharp in x64 with double precision

### ISSUE THREAD

**Issue by publicENEMY** [AndresTraks/BulletSharp#27]
I can compile bulletsharp x64 fine without double precision. To use double precision, i checked in cmake USE_DOUBLE_PRECISION, uncomment line #define BT_USE_DOUBLE_PRECISION in Stdafx.h as per your instruction. bullet can compile just fine. but bulletsharp give these errors.

Error	8	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	310	1	BulletSharp
Error	9	error C2660: 'BulletSharp::IDebugDraw::DrawAabb' : function does not take 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	310	1	BulletSharp
Error	10	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	318	1	BulletSharp
Error	11	error C2664: 'void BulletSharp::IDebugDraw::DrawArc(OpenTK::Vector3 %,OpenTK::Vector3 %,OpenTK::Vector3 %,btScalar,btScalar,btScalar,btScalar,OpenTK::Graphics::Color4,bool)' : cannot convert argument 8 from 'bool' to 'OpenTK::Graphics::Color4'	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	318	1	BulletSharp
Error	12	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	326	1	BulletSharp
Error	13	error C2661: 'BulletSharp::IDebugDraw::DrawArc' : no overloaded function takes 8 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	326	1	BulletSharp
Error	14	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	332	1	BulletSharp
Error	15	error C2664: 'void BulletSharp::IDebugDraw::DrawBox(OpenTK::Vector3 %,OpenTK::Vector3 %,OpenTK::Matrix4d %,OpenTK::Graphics::Color4)' : cannot convert argument 3 from 'OpenTK::Matrix4d' to 'OpenTK::Graphics::Color4'	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	332	1	BulletSharp
Error	16	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	338	1	BulletSharp
Error	17	error C2661: 'BulletSharp::IDebugDraw::DrawBox' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	338	1	BulletSharp
Error	18	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	343	1	BulletSharp
Error	19	error C2660: 'BulletSharp::IDebugDraw::DrawCapsule' : function does not take 4 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	343	1	BulletSharp
Error	20	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	348	1	BulletSharp
Error	21	error C2660: 'BulletSharp::IDebugDraw::DrawCone' : function does not take 4 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	348	1	BulletSharp
Error	22	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	354	1	BulletSharp
Error	23	error C2660: 'BulletSharp::IDebugDraw::DrawContactPoint' : function does not take 4 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	354	1	BulletSharp
Error	24	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	359	1	BulletSharp
Error	25	error C2660: 'BulletSharp::IDebugDraw::DrawCylinder' : function does not take 4 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	359	1	BulletSharp
Error	26	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	365	1	BulletSharp
Error	27	error C2661: 'BulletSharp::IDebugDraw::DrawLine' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	365	1	BulletSharp
Error	28	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	371	1	BulletSharp
Error	29	error C2661: 'BulletSharp::IDebugDraw::DrawLine' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	371	1	BulletSharp
Error	30	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	376	1	BulletSharp
Error	31	error C2660: 'BulletSharp::IDebugDraw::DrawPlane' : function does not take 3 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	376	1	BulletSharp
Error	32	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	381	1	BulletSharp
Error	33	error C2661: 'BulletSharp::IDebugDraw::DrawSphere' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	381	1	BulletSharp
Error	34	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	386	1	BulletSharp
Error	35	error C2661: 'BulletSharp::IDebugDraw::DrawSphere' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	386	1	BulletSharp
Error	36	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	393	1	BulletSharp
Error	37	error C2664: 'void BulletSharp::IDebugDraw::DrawSpherePatch(OpenTK::Vector3 %,OpenTK::Vector3 %,OpenTK::Vector3 %,btScalar,btScalar,btScalar,btScalar,btScalar,OpenTK::Graphics::Color4)' : cannot convert argument 9 from 'btScalar' to 'OpenTK::Graphics::Color4'	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	393	1	BulletSharp
Error	38	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	400	1	BulletSharp
Error	39	error C2664: 'void BulletSharp::IDebugDraw::DrawSpherePatch(OpenTK::Vector3 %,OpenTK::Vector3 %,OpenTK::Vector3 %,btScalar,btScalar,btScalar,btScalar,btScalar,OpenTK::Graphics::Color4)' : cannot convert argument 9 from 'btScalar' to 'OpenTK::Graphics::Color4'	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	400	1	BulletSharp
Error	40	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	407	1	BulletSharp
Error	41	error C2661: 'BulletSharp::IDebugDraw::DrawSpherePatch' : no overloaded function takes 8 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	407	1	BulletSharp
Error	42	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	418	1	BulletSharp
Error	43	error C2661: 'BulletSharp::IDebugDraw::DrawTriangle' : no overloaded function takes 4 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	418	1	BulletSharp
Error	44	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	425	1	BulletSharp
Error	45	error C2661: 'BulletSharp::IDebugDraw::DrawTriangle' : no overloaded function takes 7 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\DebugDraw.cpp	425	1	BulletSharp
Error	46	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\RaycastVehicle.cpp	171	1	BulletSharp
Error	47	error C2661: 'BulletSharp::IDebugDraw::DrawLine' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\RaycastVehicle.cpp	171	1	BulletSharp
Error	48	error C2668: 'OpenTK::Graphics::Color4::Color4' : ambiguous call to overloaded function	e:\Users\iJam\Source\Tutorial\BulletSharp\src\RaycastVehicle.cpp	172	1	BulletSharp
Error	49	error C2661: 'BulletSharp::IDebugDraw::DrawLine' : no overloaded function takes 2 arguments	e:\Users\iJam\Source\Tutorial\BulletSharp\src\RaycastVehicle.cpp	172	1	BulletSharp
Error	71	error C2440: '=' : cannot convert from 'OpenTK::Vector3d' to 'OpenTK::Vector3'	e:\Users\iJam\Source\Tutorial\BulletSharp\src\KinematicCharacterController.cpp	559	1	BulletSharp

**Comment by AndresTraks** [comment]
Try the latest commit.

**Comment by publicENEMY** [comment]
I can confirm the latest commit fixed this. thanks.

**Comment by AndresTraks** [comment]
Thanks for reporting!
