### ISSUE TITLE
Margin settings CupsuleShape

### ISSUE THREAD

**Issue by tam7832** [AndresTraks/BulletSharp#28]
Hi, I'm sorry in a frequent question.

We are using Version2.82
ConvexShape.GetAabbSlow an object that has been created in CapsuleShape
The I called. Results value added is Margin was obtained.
But if you change the Margin=0 result does not change.

Is there a good solution

**Comment by AndresTraks** [comment]
Do you mean the AABB doesn't change when you do this?

    var capsule = new CapsuleShape(1.0f, 1.0f);
    Vector3 aabbMin, aabbMax;
    capsule.GetAabbSlow(Matrix.Identity, out aabbMin, out aabbMax);
    capsule.Margin = 0;
    capsule.GetAabbSlow(Matrix.Identity, out aabbMin, out aabbMax);

**Comment by tam7832** [comment]
That's right
I tried to put the same code.
Result
aabbMin{X:-1.04 Y:-1.58 Z:-1.04}
aabbmax{X:1.04 Y:1.58 Z:1.04}

**Comment by AndresTraks** [comment]
Changing the margin has a different effect depending on the collision shape. There is some information on this in the manual:
https://github.com/bulletphysics/bullet3/blob/master/docs/Bullet_User_Manual.pdf
