### ISSUE TITLE
KeyNotFound when removing action

### ISSUE THREAD

**Issue by ShawnM427** [AndresTraks/BulletSharp#29]
So I'm working on some code to move an object from one physics world to another. The basic idea is that I'm using a PairCachingGhostObject that checks to see if any objects are outside of a space-ships bounds. If they are, then I need to move them to the main physics world. The code I use looks like this:

    _internalWorld.World.RemoveCollisionObject(e);
    _world.World.AddCollisionObject(e);
    e.WorldTransform = _physicsBody.WorldTransform * e.WorldTransform;

    IActionCollection pObj = e.UserObject as IActionCollection;

    if (pObj != null)
    {
        IAction[] connectedActions = pObj.Actions.ToArray();

        for (int i = 0; i < connectedActions.Length; i++)
        {
            _internalWorld.World.RemoveAction(connectedActions[i]);
            _world.World.AddAction(connectedActions[i]);
        }
    }

where <i>e</i> is a collision object, and IActionCollection is simply an interface to access an action collection. My issue arises at the following line:
    
    _internalWorld.World.RemoveAction(connectedActions[i]);

Here it throws a KeyNotFoundException. I looked into the source and noticed this (line 107 of DynamicWorld.cpp):

    _actions->Remove(action);
    ActionInterfaceWrapper* wrapper = (ActionInterfaceWrapper*)_actions[action].ToPointer();
    Native->removeAction(wrapper);

(I don't have much experience in c++, but this looks like this removes the action first, then tries to use it as a lookup)

I don't know if this is an issue in the bulletSharp code, or my code, so any advice would be great.
Thanks!

**Comment by AndresTraks** [comment]
Looks like I forgot to finish that piece of code. It should be fixed now, but I'll review it later. Thanks for reporting!

**Comment by AndresTraks** [comment]
Added tests for IAction add/remove in https://github.com/AndresTraks/BulletSharp/commit/d0303a2c5e463ceb33ec1a9c5c469e577f9c5f08.
