### ISSUE TITLE
Xamarin.Android and Xamarin.iOS support

### ISSUE THREAD

**Issue by amerkoleci** [AndresTraks/BulletSharp#30]
Any plans to support those 2 platforms?
Paradox3D game engine has support for this one.

**Comment by AndresTraks** [comment]
Paradox3D uses the P/Invoke version of BulletSharp (https://github.com/AndresTraks/BulletSharpPInvoke), so I'm pretty sure that'll also work on Xamarin, but I haven't checked.

C++/CLI isn't suppported on any mobile .NET platform AFAIK, so don't count on this version.

**Comment by amerkoleci** [comment]
Closing here will open on PInvoke side
