### ISSUE TITLE
cannot compile BulletSharp on Windows x64 for use with OpenTK

### ISSUE THREAD

**Issue by Arj611** [AndresTraks/BulletSharp#32]
Hey ,
I am trying to compile bulletsharp with openTK but i am faced with this error "error C2871: 'OpenTK' : a namespace with this name does not exist". I read a few articles online regarding this and I figured out that the target .NET framework version difference between openTK and bulletsharp can cause this problem. I tried resolving it but it still didnt work. Can you please help me out in solving this issue. Thanks in advance.

**Comment by AndresTraks** [comment]
Hi, try uninstalling and reinstalling OpenTK and make sure it's the latest version (1.1.4, 2014-07-23). This has worked for me.
Also, do you have MonoGame installed? MonoGame also adds OpenTK to the global assembly cache, which might interfere with the official installer, even though it should also work.

**Comment by Arj611** [comment]
That worked...thanks a lot.. Please consider adding this to the build intructions. That would be of great help.

**Comment by AndresTraks** [comment]
Cool, glad it works.
I can add it to the instructions, but it would be good to first figure out why this happens. Does an earlier OpenTK installer not install into the GAC? Does MonoGame or some other library interfere with it? Or maybe it's something else.

**Comment by Arj611** [comment]
I think its something else. I dont have monogame installed. The older version of opentk which i was using, was installed exactly the similar way i have installed the latest version.

It would be great if you could help me out on another uses case issue. I am using the bullet sharp within my application to detect collision between two traingles. I want to give the triangle vertices as input.Iff you have time,  Can u guide me on a way I can do that. These triangles are from the triangle mesh loaded through a CAD file. I basically want a triangle triangle collision test that runs on gpu and is extremly fast.

**Comment by AndresTraks** [comment]
You would generally use a BvhTriangleMeshShape for non-moving bodies, a ConvexHullShape for moving convex bodies and a GImpactMeshShape or CompoundShape for moving concave bodies. These work on the CPU. There are usage examples in the demos (e.g. ConvexDecompositionDemo, GImpactTestDemo, DistanceDemo).

BulletSharp doesn't yet wrap the Bullet 3 GPU code since it's work in progress. I'm not very familiar with it either, but you could check the examples to see if there is something that you're looking for.

**Comment by AndresTraks** [comment]
The OpenTK reference is now handled by NuGet. I'll close this issue.
