### ISSUE TITLE
System.AccessViolationException 

### ISSUE THREAD

**Issue by vutranclan** [AndresTraks/BulletSharp#33]
[soft.txt](https://github.com/AndresTraks/BulletSharp/files/130617/soft.txt)
if i try too read Scti from RigidContacts i get System.AccessViolationException error. Player is a SoftBody.

        public override void OnHandleInput()
        {
            if (Input.KeysPressed.Contains(Keys.F))
            {
                for (int i = 0; i < player.RigidContacts.Count; i++)
                {
                    var test = player.RigidContacts[i].Scti;
                }
            }
        }

**Comment by AndresTraks** [comment]
Should be fixed now, will test it a bit later.

**Comment by AndresTraks** [comment]
I also renamed Scti to ContactInfo to make it clearer.

**Comment by vutranclan** [comment]
thank you. can you send me the dll ? i dont have the sources etc to build it on my own. would be very thankfull !

**Comment by vutranclan** [comment]
Hello could you explain to me, how i compile your code to make a dll to use
it in c# ?
greetings from germany huy

2016-02-15 15:53 GMT+01:00 Andres Traks <notifications@github.com>:

**Comment by AndresTraks** [comment]
I put it here temporarily: https://drive.google.com/file/d/0B2TPMwtggT0jaXhwNHJTYmNtTzA/view?usp=sharing
Oh, and thanks for the report!

**Comment by vutranclan** [comment]
thank you but when i replace the dll in your example it doesnt work i got
these errors:

mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile,
System.Security.Policy.Evidence assemblySecurity, string[] args)
Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext
executionContext, System.Threading.ContextCallback callback, object state,
bool preserveSyncCtx)
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext
executionContext, System.Threading.ContextCallback callback, object state,
bool preserveSyncCtx)
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext
executionContext, System.Threading.ContextCallback callback, object state)
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()


here is it:
https://www.dropbox.com/s/gsetlm9fi34jypl/bulletsharp-demos-2.83.7%20with%20dllupdate.zip?dl=0


2016-02-17 12:33 GMT+01:00 Andres Traks <notifications@github.com>:

**Comment by AndresTraks** [comment]
There are changes in the repository that are incompatible with the older demo code. I'd recommend switching to Visual Studio 2015 (Community edition, which is free) and using the latest code from the repository. Also select Visual C++ tools during installation so you could [compile Bullet and BulletSharp](https://github.com/AndresTraks/BulletSharp/wiki/Build-instructions).

Sorry about that, but I'd prefer not to put time on compiling and distributing binaries too often. The build process should be relatively easy if you follow the instructions, but let me know if there are any problems.
