### ISSUE TITLE
SoftBody.SoftContacts has no properties

### ISSUE THREAD

**Issue by vutranclan** [AndresTraks/BulletSharp#34]
SoftBody sb;
            sb= SoftBodyHelpers.CreateEllipsoid(demo.softBodyWorldInfo, pPosition, new Vector3(3, 3, 3), 512);
            sb.Materials[0].Lst = 0.1f;
            sb.Cfg.DF = 1;
            sb.Cfg.DP = 0.001f; // fun factor...
            sb.Cfg.PR = 2500;
            sb.SetTotalMass(30, true);
            demo.SoftWorld.AddSoftBody(sb);

                foreach (var SoftContact in sb.SoftContacts)
                {
                    // no properties or function 
                    //SoftContact.?
                }

**Comment by AndresTraks** [comment]
Oops, the public: access specifier was accidentally commented out. It's fixed now. Thanks!
