### ISSUE TITLE
Method CheckCollideWith

### ISSUE THREAD

**Issue by vutranclan** [AndresTraks/BulletSharp#36]
I want to check if two rigidbodys colide with each other,

RigidBody br;
RigidBody br2;
....
...
br.CheckCollideWith(br2 as CollisionObject); // always true!

Also Softbody.CheckCollideWith doesnt seem to work right.

**Comment by AndresTraks** [comment]
CheckCollideWith returns whether Bullet should check for collisions between two bodies, not whether collisions have occured.

This page shows how you can check for collisions:
https://github.com/AndresTraks/BulletSharp/wiki/Collision-Callbacks-and-Triggers
