### ISSUE TITLE
Problems with boxshapes

### ISSUE THREAD

**Issue by AndresLeonardoMartinez** [AndresTraks/BulletSharp#38]
Hi!
I have some problems with box shapes. 
I try to make a simple example: a box falling on to a surface.
I'm drawing the box with the Model Matrix providing by BoxRigidBody->MotionState() -> getWorldTransform() . Is this the correct form?
When I work with sphere shape I don't have any problem, but yes when I work with box Shape. The box touchs the surface (StaticPlaneShape ) and its model matrix returns a strange behavior. 
Hope someone can help me.
Regads,
Andres

**Comment by AndresTraks** [comment]
Hi!
Maybe your graphics framework has a different layout for matrices than BulletSharp.
Try transposing the matrix that you get from the motion state.

**Comment by AndresLeonardoMartinez** [comment]
Hi! 
Thanks for your response.
Here the code:
phisics class:

`private void inicializarMundo()
        {cantidad = 1;
            broadphase = new DbvtBroadphase();
            collisionConfiguration = new DefaultCollisionConfiguration();
            dispatcher = new CollisionDispatcher(collisionConfiguration);
            //solver = new SequentialImpulseConstraintSolver();
            //mundo
            DynamicsWorld = new DiscreteDynamicsWorld(dispatcher, broadphase, null, collisionConfiguration);
            DynamicsWorld.Gravity = new Vector3(0, -10, 0);
            //aca se realizan las acciones
            CollisionShape groundShape = new StaticPlaneShape(new Vector3(0, 1, 0), 0);
            DefaultMotionState myMotionState = new DefaultMotionState(Matrix4.CreateTranslation(0, -1, 0));
            RigidBodyConstructionInfo rbInfo = new RigidBodyConstructionInfo(0, myMotionState, groundShape, new Vector3(0, 0, 0));
            Rplano = new RigidBody(rbInfo);

            DynamicsWorld.AddRigidBody(Rplano);


            //    CollisionShape fallShape = new SphereShape(1);
            //esfera 1
            for (int i = 0; i < cantidad; i++)
            {
                CollisionShape esf2 = new **SphereShape**(1);
                //Matrix4 M =Matrix4.Mult( Matrix4.CreateRotationZ(0.2f), Matrix4.CreateTranslation(0, 20 + 2 * i, 0));
                Matrix4 M = Matrix4.CreateTranslation(new Vector3(0, 8 + 2 * i, 0));
                ListaMV.Add(M);
                DefaultMotionState fallMotionState2 = new DefaultMotionState(M);
                Vector3 localInertia2 = esf2.CalculateLocalInertia(1);
                RigidBodyConstructionInfo fallRigidBodyCI2 = new RigidBodyConstructionInfo(1, fallMotionState2, esf2, localInertia2);
                fallRigidBody = new RigidBody(fallRigidBodyCI2);
                ListaRB.Add(fallRigidBody);

                DynamicsWorld.AddRigidBody(fallRigidBody);


            }`
I'm working with OpenTK 1.1, Visual Studio 2015 in a windows form. 
Here the code of the timer:
`        private void timer1_Tick(object sender, EventArgs e)
        {
            fisica.DynamicsWorld.StepSimulation(10);
            
            for (int i = 0; i < fisica.getCantidad(); i++)
            {
                // Matrix4 M = fisica.ListaRB[i].MotionState.WorldTransform;
                // M.Transpose();
                // fisica.ListaMV[i] = M;
                fisica.ListaMV[i] = fisica.ListaRB[i].MotionState.WorldTransform;

            }
           glControl3.Invalidate();

        }`
Result with SphereSharp: [https://youtu.be/4HKtbGSU2Og](url)
Result with BoxSharp:[https://youtu.be/XDFeHNSXHtM](url)

**Comment by AndresLeonardoMartinez** [comment]
Forget all:
I had a problem in the form of multiply the model with the View.
Again: thanks for the code!
Regards,
Andres

**Comment by AndresTraks** [comment]
Ok, cool!
