### ISSUE TITLE
[BUG v2.83.7] remove collision object from physic world

### ISSUE THREAD

**Issue by nerogcy** [AndresTraks/BulletSharp#42]
Hi, i found some bug when i try to remove collision object from physic world on version 2.83.7. When i remove it reference to the wrong collision object. I believe this is a bug, because when i switch back to version 2.83.5, it work fined.

[Here is version 2.83.7]
![work2](https://cloud.githubusercontent.com/assets/20985725/17615440/eb9e8b7e-60a0-11e6-9311-a1b9d8deb722.gif)

[Here is version 2.83.5]
![work1](https://cloud.githubusercontent.com/assets/20985725/17615404/add7e8bc-60a0-11e6-8250-3002ab9b9a4e.gif)

**Comment by AndresTraks** [comment]
Hi, did you try the latest version from git?
This may have been fixed here: https://github.com/AndresTraks/BulletSharp/issues/39

**Comment by nerogcy** [comment]
oic, thanks alot... can you help me to build a new release file? i cant build from your source.

**Comment by AndresTraks** [comment]
It's unfortunate that there hasn't been a Bullet release in a while, so I can't keep the same versioning scheme. I'll try to do a release within in the next week or so.

**Comment by nerogcy** [comment]
Great, thank you very much.

**Comment by AndresTraks** [comment]
Here it is: https://github.com/AndresTraks/BulletSharp/releases

**Comment by nerogcy** [comment]
thanks..  :)
