### ISSUE TITLE
Update NuGet package to use SharpDX >= 3

### ISSUE THREAD

**Issue by epicabsol** [AndresTraks/BulletSharp#43]
Right now the NuGet package references SharpDX 2.6.3, which is a pain when the current version is 3.0.2.

**Comment by AndresTraks** [comment]
The SharpDX references in BulletSharp have already been updated to 3.0.2 in the repository. There will be a release of BulletSharp in August with the SharpDX update, maybe even today if all goes to plan. :)

**Comment by epicabsol** [comment]
Awesome, thanks!

**Comment by AndresTraks** [comment]
Here it is: https://github.com/AndresTraks/BulletSharp/releases
