### ISSUE TITLE
Why samples from release doesn't use BulletSharp 0.9.0 ?

### ISSUE THREAD

**Issue by patsadow2** [AndresTraks/BulletSharp#44]
Hello,

When i try to use Demos from release, MonoGame lib from nuget and bulletSharp.dll for monogame from release i;ve got cross reference for example with Vector3 -> Microsoft.Xna.Framework and BulletSharp. What should i do to make it run correctly ?

**Comment by AndresTraks** [comment]
Hi,
Nuget hosts the [PInvoke version of BulletSharp](https://github.com/AndresTraks/BulletSharpPInvoke). The samples for it are slightly different: https://github.com/AndresTraks/BulletSharpPInvoke/tree/master/BulletSharpPInvoke/demos

I've been thinking of deprecating the C++/CLI version even though it has some benefits (better integration with other libraries, double precision, slightly better performance). But I also understand that having two versions is a bit confusing. :/
