### ISSUE TITLE
Hi Vb.net developer issue when I try to remove ridgid body!!!

### ISSUE THREAD

**Issue by tridexanders** [AndresTraks/BulletSharp#46]
1. am using a 64bit version of the System.Numerics version, every thing working great until I try to remove a rigid object form the world !!! 

2. Me.World.RemoveRigidBody(body)

3. not that remove does remove as the world CollisionObjectArray is decremented

4. on the next frame step of the simulation you suddenly get an AcccessViolation Exception? , i have tried disposing of motion states e.t.c but to no effect??? arrrgh, all I want to do is remove an object form the world!!!

5. How can I freely remove an object from the simulation... checking on google a few people seem to have this issue?

-----------------------------------------------------------------------------------------------------------
thanks and great work, much faster, and I am amazed you guys got system numerics to work with your engine, brilliant work!!!

**Comment by tridexanders** [comment]
Hi forgot to ask how to make donations to your project?

**Comment by tridexanders** [comment]
OK FIXED!!!!! my error i was add duplicate Rigidbodies to the world!!!! is some code areas, after confirm Scene object counts against collider, noticed duplcaties every time i was creating a physics rigidbody!!! so on fixing that ALL IS FANTASTICALY GOOD..  EXCELLENT!!

Thanks and how to i donate to you guys ...

**Comment by AndresTraks** [comment]
Thanks!

Donations can be sent here: https://www.paypal.me/AndresTraks
