### ISSUE TITLE
Stop simulate

### ISSUE THREAD

**Issue by AndresLeonardoMartinez** [AndresTraks/BulletSharp#47]
Hi! I'm having some troubles whit the simulation, I thing.
I use OpenTK with a glControl (not a game window). 
I have a timer:

```
 private void timer1_Tick(object sender, EventArgs e)
        {
            physics.DynamicsWorld.StepSimulation(15);
...
//more code here
            glControl3.Invalidate();

}

```
In the world there are a ground and boxes. 
When the key 'g' is pressed (glControl3_KeyPress), it calls to applyForce. I created a method in physics class:
```
 public void aplyForce(Vector3 fce) {
            RigidBody R = ListRB[ListRB.Count-1]; //the last box
            R.ApplyImpulse(fce, new Vector3(0));
        }
```
      
It works perfectly but when I stop to interact with the keys and not collisions occurs (by 2, 3 seconds) applyForce stop to work!
I created another method that add a new box to the world. It works and applyForce back to work again (remember is the last box of the world)

**Comment by AndresTraks** [comment]
Hi!
StepSimulation arguments are in seconds.
Are you sure it's supposed to be 15 seconds and not 15 milliseconds (0.015 seconds)?

**Comment by AndresLeonardoMartinez** [comment]
I changed the step simulate to:

`physics.DynamicsWorld.StepSimulation(50/100);`

But the problem doesn't disappear. 
The timer is: 50 milliseconds

**Comment by AndresTraks** [comment]
In C#, integer divisions are rounded down, so you get 50/100 = 0.0f.
Use 50.0f/1000.0f to get 50 milliseconds in seconds (1 second = 1000 milliseconds).

I think you want the time step to be the same as the timer interval, but the .NET Timer class works with milliseconds while Bullet uses seconds.
So use an interval of 50 milliseconds for the Timer and a time step of 50.0f/1000.0f seconds for Bullet.

**Comment by AndresLeonardoMartinez** [comment]
Thanks again, but is the same problem.
When the collisions stop and there aren't moves in the world (or key press) for 2 or 3 seconds the applyforce doesn't work. 
If there aren't moves physic simulation changes its state? Maybe a stationary state?
Maybe I should change from glControl whit timer to Game Window

**Comment by AndresTraks** [comment]
If no time passes in the simulation (StepSimulation is not called), then nothing moves.

The effect of changing the impulse can be seen only after the simulation is stepped.

**Comment by AndresLeonardoMartinez** [comment]
I did not express myself correctly:
now:
`physics.DynamicsWorld.StepSimulation(50.0f/1000.f); `
But the problem doesn't disappear

**Comment by AndresTraks** [comment]
Ok, I see what you mean.
Bullet has a feature where bodies that haven't moved a lot become "inactive". This is for improving performance. Impulses are not applied to inactive bodies.

You can either:
1) activate the bodies by calling R.Activate() before calling ApplyImpulse or
2) when creating the body, set R.ActivationState = ActivationState.DisableDeactivation so the body never gets deactivated.

**Comment by MarinaRazuc** [comment]
```
R.Activate();
R.ApplyImpulse(fce, new Vector3(0));
```
Its Works!
Thanks a lot!

**Comment by AndresLeonardoMartinez** [comment]
```
R.Activate();
R.ApplyImpulse(fce, new Vector3(0));
```
Its Works!
Thanks a lot!

**Comment by AndresTraks** [comment]
Awesome!
