### ISSUE TITLE
Bullet Physics Version Update

### ISSUE THREAD

**Issue by balajiraghuram92** [AndresTraks/BulletSharp#49]
Hi,

The bullet physics Version used in your project is 2.8.3

Will there be any update to 2.8.6 or can you help me out how do i update the Project to latest bullet physics SDK.

**Comment by AndresTraks** [comment]
Yes, I'm just finishing some things like adding multithreading and upgrading graphics frameworks.

**Comment by AndresTraks** [comment]
2.87 is released now.

**Comment by balajiraghuram92** [comment]
Hi,
Is this the latest sdk with Bullet physics 2.87 implementation or latest bullet physics implementation.

Can you give me the link for the source, because I saw the last update or commit on project was 8 months ago for generic.

Thank you very much for your support

**Comment by AndresTraks** [comment]
I used the latest repository versions from yesterday, so:
https://github.com/bulletphysics/bullet3/tree/c149840264dacb7daed46782bb5c02a4248ade53
https://github.com/AndresTraks/BulletSharp/tree/aeeda3814df41e79f753f32bdbfb0c77e7bade08

The 2.x branch isn't being updated much, so I expect that BulletSharp can also be compiled against the exact Bullet 2.87 release version.
