### ISSUE TITLE
MultiThreadedDemo, A heap has been corrupted exception

### ISSUE THREAD

**Issue by stampergames** [AndresTraks/BulletSharp#51]
Hi Andres,

The MultiThreadedDemo application is throwing an exception when I attempt to run it.   Below is the exception.

Unhandled exception at 0x77929ABA (ntdll.dll) in MultiThreadedDemo.exe: 0xC0000374: A heap has been corrupted (parameters: 0x779658E8).

It functions properly when using the sequential task scheduler but fails when attempting to use the Open MP task scheduler or the Ppl Task Scheduler.  The Tbb Task Scheduler is not available on my machine.  When configuring/re-building Bullet, I have selected BULLET2_USE_THREAD_LOCKS, BULLET2_USE_OPEN_MP_MULTITHREADING and  BULLET2_USE_PPL_MULTITHREADING.  I have built both Bullet and BulletSharp in Release/Win32 mode.

Below is the stack trace.  

>	ntdll.dll!_RtlReportCriticalFailure@12()	Unknown
 	ntdll.dll!_RtlpReportHeapFailure@4()	Unknown
 	ntdll.dll!_RtlpHeapHandleError@4()	Unknown
 	ntdll.dll!_RtlpLogHeapFailure@24()	Unknown
 	ntdll.dll!RtlpInsertFreeBlock()	Unknown
 	ntdll.dll!RtlpDeCommitFreeBlock()	Unknown
 	ntdll.dll!RtlpFreeHeap()	Unknown
 	ntdll.dll!RtlFreeHeap()	Unknown
 	ucrtbase.dll!_free_base()	Unknown
 	ucrtbase.dll!_free()	Unknown
 	BulletSharp.dll!btAlignedAllocSetCustomAligned(void * (*)(unsigned int,int),void (*)(void *))	C++
 	BulletSharp.dll!btSequentialImpulseConstraintSolver::getOrInitSolverBody(class btCollisionObject &,float)	C++
 	BulletSharp.dll!btSequentialImpulseConstraintSolver::solveGroupCacheFriendlySetup(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *)	C++
 	BulletSharp.dll!btSequentialImpulseConstraintSolver::solveGroup(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *,class btDispatcher *)	C++
 	BulletSharp.dll!InplaceSolverIslandCallbackMt::processIsland(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,int)	C++
 	BulletSharp.dll!UpdateIslandDispatcher::forLoop(int,int)	C++
 	BulletSharp.dll!btSpinMutex::lock(void)	C++
 	vcomp140.dll!_vcomp::fork_helper(void(*)() funclet, int arg_count, char * argptr) Line 363	C++
 	vcomp140.dll!_vcomp::fork_helper_wrapper(void(*)() funclet, int arg_count, char * argptr) Line 324	C++
 	vcomp140.dll!_vcomp::ParallelRegion::HandlerThreadFunc(void * context, unsigned long index) Line 303	C++
 	vcomp140.dll!_vcomp::PersistentThreadFunc(void * pvContext) Line 240	C++
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by AndresTraks** [comment]
Yeah, I get that too.
It seems like either 1) the wrapper allocates some object without proper alignment or 2) the wrapper tries to deallocate some object without considering alignment.
I can look at this closer on Sunday. It works in BulletSharp P/Invoke.

**Comment by AndresTraks** [comment]
Fixed in https://github.com/AndresTraks/BulletSharp/commit/59208937cddcb955f0a71e7fb7c4927ad72b2b8d.
Thanks for the report!

**Comment by stampergames** [comment]
Thanks for the fix!  Works great!
