### ISSUE TITLE
Build instructions for non C++ developers

### ISSUE THREAD

**Issue by Behemoth-of-Tenkarrdun** [AndresTraks/BulletSharp#52]
So, first off, I'm sorry I'm a total idiot when it comes to C++.  I had to Google CMake to figure out what it was.

However, I imagine a fair number of people want to use this library for similar reasons.  If we were half competent with C++, we'd just use a C++ library.  However, the Build instructions for Bullet Sharp are seriously lacking for people that don't know how to do normal C++ tasks.  Step 2 of "Generate Bullet solution files with CMake-gui. Set the build directory" just leaves me in the dust.  I've never used CMake, and I've no idea what it's doing or how to use it.  I took stabs at the source code folder and build output folder, clicked configure and watched the red text fly by.

If the solution is "just use the out-dated Nuget build", then I suppose it will have to do, but it isn't kept up to date with the Github project here.  However, the Demos project doesn't even compile against the Nuget package right now.

I have CMake and VS 2017 Pro installed with C/C++ tools as per the Prerequisites.

**Comment by AndresTraks** [comment]
The Nuget package is a different version of BulletSharp with its own demos and build instructions:
https://github.com/AndresTraks/BulletSharpPInvoke

Most of the recent improvements in Bullet are for the robotics part, which BulletSharp does not cover yet. The Nuget build is pretty much up to date when it comes to the core of the Bullet library.

I can't give you shortcuts to learning CMake or C++. It is what it is. If you get errors in CMake, you can ask about them here and I'll help you out.

**Comment by Behemoth-of-Tenkarrdun** [comment]
Just using the releases here on Github, then.
