### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by DSysdev** [AndresTraks/BulletSharp#57]
Hi,

Apologies if this is not a BulletSharp issue. Not sure if this issue is due to my usage of BulletSharp or some other problem.

I encountered a problem with collision detection when applying translation after scaling to the object center of mass. Applying the translation only after setting the initial box shape dimensions to the scaling I want works correctly.

Case1: Box shape size 1 -> apply scaling -> apply translation -> update object -> contact test
Case2: Box shape scale size -> apply translation -> update object -> contact test

What is strange is that the final vertices appear to be the same in both cases but I am only getting a collision in the second case.

Any idea what might be the issue? I can write small project showing the problem if that helps.

Many Thanks!

**Comment by AndresTraks** [comment]
Hi!
Can you show the code where you are applying the scaling?
Bullet does not directly support scaling of rigid collision objects. The transform of the center of mass cannot be scaled either.
If you need to change the scale of an existing object, then what you could try is to change the LocalScaling parameter of the collision shape and then clear collision pairs in the broadphase with any existing collision objects.

**Comment by DSysdev** [comment]
Sure the basic scaling code is below. If there is a second transformation I multiply it with the scaling.

Code:
```
body.CenterOfMassTransform = Matrix.Scaling(XScaling, YScaling, ZScaling);
World.UpdateSingleAabb(body);
```

Just to add; if I apply scaling only (i.e. no translation) it appears to be working fine:
- 2 identical boxes away from each other -> no collision
- Scale one of those boxes to cover the separation distance -> collision

**Comment by DSysdev** [comment]
Thanks! That is the only thing that worked so far. Even the LocalScaling didn't work.

In the interest of reducing as much overhead when creating new body as possible, is there a method to just update the object shape?

Looking around there seems to be a function: `object->setCollisionShape(newShape)` - but in BulletSharp `object.CollisionShape` is read-only.
