### ISSUE TITLE
Provide a nuget package to allow easy restore in projects.

### ISSUE THREAD

**Issue by LaylConway** [AndresTraks/BulletSharp#7]
I generally in my projects have all my dependencies managed by nuget, so they're automatically restored on build and do not have to be included in the repository. It would be great if BulletSharp could also get a nuget package so I can use it in the same way.

**Comment by dazerdude** [comment]
+1

**Comment by AndresTraks** [comment]
NuGet doesn't play nicely with platform-dependent assemblies yet:
http://nuget.codeplex.com/workitem/679

Looks like they're fixing this in NuGet 3.0. Until then I won't bother hacking around it.

**Comment by rejurime** [comment]
Hi there!
Are there any news about the nuget package? :smile: 
Regards.

**Comment by AndresTraks** [comment]
Hi!
I'm thinking of putting up the PInvoke version of BulletSharp since it's cross-platform and getting more and more stable.
What I haven't figured out is how to copy the right version of libbulletc.dll to the output directory based on the target platform (x86, x64, AnyCPU).

**Comment by rejurime** [comment]
Maybe this could help you:
* https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

**Comment by AndresTraks** [comment]
Thanks, René! That made things a lot easier.
BulletSharp PInvoke is now on nuGet: https://www.nuget.org/packages/BulletSharp/

The solution to copying libbulletc.dll was to use a .targets file.

**Comment by rejurime** [comment]
Nice work! I'll use it :wink:
